---
name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          $(go env GOPATH)/bin/staticcheck ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
      - name: Show test coverage
        run: make coverage
      - name: Check test coverage threshold
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.github/testcoverage.yml
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Build
        run: make build
